// quotes.js
const quotes = [
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "The way to get started is to quit talking and begin doing. - Walt Disney",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "If life were predictable it would cease to be life, and be without flavor. - Eleanor Roosevelt",
    "Life is what happens when you're busy making other plans. - John Lennon",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Tell me and I forget. Teach me and I remember. Involve me and I learn. - Benjamin Franklin",
    "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart. - Helen Keller",
    "It is during our darkest moments that we must focus to see the light. - Aristotle",
    "Whoever is happy will make others happy too. - Anne Frank",
    "Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson",
    "You will face many defeats in life, but never let yourself be defeated. - Maya Angelou",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "In the end, it's not the years in your life that count. It's the life in your years. - Abraham Lincoln",
    "Never let the fear of striking out keep you from playing the game. - Babe Ruth",
    "Life is either a daring adventure or nothing at all. - Helen Keller",
    "Many of life's failures are people who did not realize how close they were to success when they gave up. - Thomas A. Edison",
    "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose. - Dr. Seuss",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "What lies behind you and what lies in front of you, pales in comparison to what lies inside of you. - Ralph Waldo Emerson",
    "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "To handle yourself, use your head; to handle others, use your heart. - Eleanor Roosevelt",
    "Too many of us are not living our dreams because we are living our fears. - Les Brown",
    "Do what you can with all you have, wherever you are. - Theodore Roosevelt",
    "You miss 100% of the shots you don't take. - Wayne Gretzky",
    "I think it is possible for ordinary people to choose to be extraordinary. - Elon Musk",
    "Everything you’ve ever wanted is on the other side of fear. - George Addair",
    "Success is going from failure to failure without losing your enthusiasm. - Winston Churchill",
    "You define your own life. Don’t let other people write your script. - Oprah Winfrey",
    "Change will not come if we wait for some other person or some other time. We are the ones we've been waiting for. We are the change that we seek. - Barack Obama",
    "It is never too late to be what you might have been. - George Eliot",
    "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "When you have a dream, you've got to grab it and never let go. - Carol Burnett",
    "I can't change the direction of the wind, but I can adjust my sails to always reach my destination. - Jimmy Dean",
    "No matter what you're going through, there's a light at the end of the tunnel. - Demi Lovato",
    "Life is like riding a bicycle. To keep your balance, you must keep moving. - Albert Einstein",
    "Just don't give up trying to do what you really want to do. Where there's love and inspiration, I don't think you can go wrong. - Ella Fitzgerald",
    "Limit your 'always' and your 'nevers.' - Amy Poehler",
    "Nothing is impossible. The word itself says 'I'm possible!' - Audrey Hepburn",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "Try to be a rainbow in someone's cloud. - Maya Angelou",
    "You do not find the happy life. You make it. - Camilla Eyring Kimball",
    "The most wasted of days is one without laughter. - E.E. Cummings",
    "You must do the things you think you cannot do. - Eleanor Roosevelt",
    "It isn’t where you came from. It’s where you’re going that counts. - Ella Fitzgerald",
    "It is never too late to be what you might have been. - George Eliot",
    "Stay close to anything that makes you glad you are alive. - Hafez",
    "You get what you give. - Jennifer Lopez",
    "Some people look for a beautiful place. Others make a place beautiful. - Hazrat Inayat Khan",
  ];
  
  export default quotes;
  